services:
  cnergy-backend:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
        - redis
        - mysql
    networks:
      - cnergy-backend-network

  redis:
    image: redis:6.0.9
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - cnergy-backend-network

  mysql:
    image: mysql
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cnergy
    networks:
      - cnergy-backend-network

volumes:
  redis-data:
  mysql-data:

networks:
  cnergy-backend-network:
      driver: bridge
